// Mocks generated by Mockito 5.4.0 from annotations
// in clean_flutter_template/test/shared/infra/repositories/directions_repository_http_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_flutter_template/shared/domain/entities/direction.dart'
    as _i2;
import 'package:clean_flutter_template/shared/infra/external/http/directions_datasource_interface.dart'
    as _i3;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDirection_0 extends _i1.SmartFake implements _i2.Direction {
  _FakeDirection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IDirectionsDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDirectionsDatasource extends _i1.Mock
    implements _i3.IDirectionsDatasource {
  MockIDirectionsDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Direction> getDirection({
    required _i5.LatLng? origin,
    required _i5.LatLng? destination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirection,
          [],
          {
            #origin: origin,
            #destination: destination,
          },
        ),
        returnValue: _i4.Future<_i2.Direction>.value(_FakeDirection_0(
          this,
          Invocation.method(
            #getDirection,
            [],
            {
              #origin: origin,
              #destination: destination,
            },
          ),
        )),
      ) as _i4.Future<_i2.Direction>);
}
