// Mocks generated by Mockito 5.4.0 from annotations
// in clean_flutter_template/test/shared/infra/repositories/procedure_repository_http_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_flutter_template/shared/domain/entities/procedure.dart'
    as _i4;
import 'package:clean_flutter_template/shared/infra/external/http/procedure_datasource_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IProcedureDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProcedureDatasource extends _i1.Mock
    implements _i2.IProcedureDatasource {
  MockIProcedureDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Procedure>> getAllProcedures() => (super.noSuchMethod(
        Invocation.method(
          #getAllProcedures,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Procedure>>.value(<_i4.Procedure>[]),
      ) as _i3.Future<List<_i4.Procedure>>);
}
